### PR TITLE
Mocked stdin should be closed to avoid hanging forever

### PR DESCRIPTION
**Pull request by tchaumeny**
See https://github.com/jdxcode/fancy-test/issues/25

Added tests to ensure stdin `end` event is triggered (previously failing)

### CODE REVIEW

**Comment by jdxcode** [comment]
This is not typical behavior when attached to the try. Usually the file stays open and does not close.

**Comment by tchaumeny** [comment]
> This is not typical behavior when attached to the file. Usually the file stays open and does not close.

What do you mean "when attached to the file" ?

In my case, I developed a CLI application and it can take inputs from stdin, but the application will hang until stdin sends an EOF. `mock-stdin` give us a way to emulate the EOF using `stdin.end()` but we have no way to call it with the current implementation in fancy-test.

**Comment by jdxcode** [comment]
Sorry, I mean tty not file

**Comment by RasPhilCo** [comment]
Cleaning up - if you think this PR is still valid, reopen it. Thanks!

**Pull request closed without merging**
